### ISSUE TITLE
Add keyboard support

### ISSUE THREAD

**Issue by cherche** [cherche/lights-out#3]
QWE-ASD-ZXC can be used to "click" on the light it corresponds to (pressing Q is like clicking on the square in the top-right).

**Comment by Bergenfrundt** [comment]
Possibly could make it so that you can assign certain keys to certain light (e.g i could do 123qweasd instead, or wersdfxcv rather than qweasdzxc

**Comment by cherche** [comment]
I suppose I could add a settings button to the "share" bar at the bottom. It could be hard to integrate this, however, as I'd need to add a cookie for it, add code to change the key, etc., but it should work quite well. Making it assign keys in a 3x3 grid would be almost impossible, as keyboards have different keyboard layouts, but setting the individual lights shouldn't be a problem.

**Comment by Bergenfrundt** [comment]
Yeah, i was  just giving the 3x3s as an example. If i wanted, i could set it to 1phvodhtu.

It'd be nice for people who find qweasdzxc inconvenient. I, myself, would prefer wersdfxcv

**Comment by cherche** [comment]
Resolved by 76c6a1d. Next step is to generalize user inputs for controlling the game.
