### ISSUE TITLE
Problem with the social media buttons

### ISSUE THREAD

**Issue by Bergenfrundt** [cherche/lights-out#5]
They are, ever so slightly (yet ever so irritatingly) taller than the white bar at the bottom.

Fucking hell.

Solution: Remove the white bar entirely, and move the buttons up a bit. The white bar completely contradicts the design philosophy of minimalism that is set up, and moving the buttons up a bit will make it look better when the white bar goes.

**Comment by cherche** [comment]
Actually, it's intentional and made to "pop". I may consider redesigning the share bar, however.

**Comment by Bergenfrundt** [comment]
It looks fuckin ugly.

**Comment by Bergenfrundt** [comment]
thanks for fixing it.

**Comment by cherche** [comment]
Technically, that was you with your font change.
