### ISSUE TITLE
Rewrite a lot of Lights Out so it looks nicer and performs better

### ISSUE THREAD

**Issue by cherche** [cherche/lights-out#6]
- Design
- Cache jQuery objects

``` javascript
var $table = $('table');
// Use $table instead of $('table') below
```
- Shrink that `flip` function; it seems to do a lot more than flip

**Comment by Bergenfrundt** [comment]
Start by fixing the damn buttons.

**Comment by cherche** [comment]
@Bergenfrundt That was actually fixed when you changed the font.

**Comment by Bergenfrundt** [comment]
I'm a god.
